---
apiVersion: batch/v1
kind: Job
metadata:
  name: docker-build-job
spec:
  template:
    spec:
      containers:
        - name: docker
          image: docker:19.03.12
          command: ["docker", "build", "-t", "myapp:latest", "/workspace"] # Construir la imagen en /workspace
          volumeMounts:
            - mountPath: /workspace
              name: workspace
      initContainers:
        - name: clone-repo
          image: alpine:3.14
          command: ["sh", "-c", "apk add --no-cache git && git clone https://github.com/youruser/yourrepo.git /workspace"] # Clona el repositorio
          volumeMounts:
            - mountPath: /workspace
              name: workspace
      restartPolicy: Never
      volumes:
        - name: workspace
          emptyDir: {}
  backoffLimit: 4

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myapp:latest  # Esta es la imagen local construida por el Job
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Puerto donde estará accesible el servicio en el nodo
  type: NodePort
