apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1  # Solo una réplica en este caso
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: nginx:alpine  # Usamos la imagen de Nginx
        ports:
        - containerPort: 80  # El puerto del contenedor
