apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: webapp.local  # Cambia esto por el dominio que quieras usar
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-app-service  # Nombre del servicio al que dirigir el tráfico
            port:
              number: 80
