apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html  # Aquí es donde Nginx busca los archivos HTML
      volumes:
        - name: nginx-html
          gitRepo:
            repository: https://github.com/jorgelsc-dev/portafolio.git  # URL del repositorio
            revision: main  # Rama del repositorio (cambia si es diferente)
            directory: /  # Ruta de los archivos dentro del repositorio (puedes ajustarlo si es necesario)
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # Puerto NodePort para acceso externo
  type: NodePort
