apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html  # Directorio de Nginx donde se montarán los archivos
      volumes:
        - name: nginx-html
          gitRepo:
            repository: https://github.com/jorgelsc-dev/portafolio.git  # URL del repositorio
            revision: main  # Rama del repositorio
            directory: .  # Ruta dentro del repositorio (en este caso, la raíz)
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
