apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app  # Debe coincidir con el label en el Deployment
  ports:
    - protocol: TCP
      port: 80  # El puerto que usará el Service
      targetPort: 80  # El puerto que usará el contenedor
  type: NodePort  # Esto expondrá el servicio en un puerto en los nodos
